### ISSUE TITLE
Creation Club Armors Upscaled Textures

### ISSUE THREAD

**Issue by CANicholson** [PierreDespereaux/Keizaal#1]
**Mod name**
Creation Club Armors Upscaled Textures

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/34526?tab=description

**Why?**
Crispy textures are required for CC stuff and the next, next update has passed

**Additional context**

**Comment by PierreDespereaux** [comment]
I wish there was an all-in-one version of this mod. I may try to make a FOMOD installer because in it's current form it is not realistic to include.

**Comment by PierreDespereaux** [comment]
This recommendation has been accepted and will be included in Keizaal 3.4.0.
