### ISSUE TITLE
Sleeves for Guards

### ISSUE THREAD

**Issue by CANicholson** [PierreDespereaux/Keizaal#10]
**Mod name**
Sleeves for guards

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/18077

**Why?**
This mod uses unused assets from the final game, which is the addition of sleeves to the typical guard/Stormcloak cuirass. Different regions have a different chance to spawn with sleeves/gloves meaning it increases the guard variety without going overboard or replacing the vanilla look

**Additional context**
When using Franklys HD guards make sure to install the fix in the updates as the original mod did not include sleeve textures.

**Comment by PierreDespereaux** [comment]
I'm going to go ahead an accept these, however I won't be adding them to Keizaal until your "final update" is out.

**Comment by PierreDespereaux** [comment]
Is Standalone Sleeves of Skyrim (#9) going to eventually consume this mod?

**Comment by CANicholson** [comment]
Yeah, that's the eventual plan. I'm currently just bogged down in life atm

**Comment by PierreDespereaux** [comment]
Gotcha, no rush of course, if you're gonna consume this mod I'll just leave it out.
