### ISSUE TITLE
Sepolcri is uncategorized and not enabled

### ISSUE THREAD

**Issue by Shade088** [PierreDespereaux/Keizaal#100]
**Keizaal version**
4.0.0

**Describe the bug**
Sepolcri is uncategorized and not enabled.

**To reproduce**
N/A

**Expected behavior**
Sepolcri to be placed under a category and enabled.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by PierreDespereaux** [comment]
Delete your installation folder (not your downloads folder) and rerun Wabbajack. It would be fixed.
