### ISSUE TITLE
CTD When Leaving Riften

### ISSUE THREAD

**Issue by Silmaril009** [PierreDespereaux/Keizaal#101]
[Crash_2021_1_29_15-48-57.txt](https://github.com/PierreDespereaux/Keizaal/files/5896975/Crash_2021_1_29_15-48-57.txt)
[Crash_2021_1_29_15-46-7.txt](https://github.com/PierreDespereaux/Keizaal/files/5896976/Crash_2021_1_29_15-46-7.txt)

**Keizaal version**
4.0.0

**Describe the bug**
Used Skyrim Unbound on random location start. Started me in Riften. When I leave Riften (to Skyrim) through any gate it causes a CTD.

**To reproduce**
Start in Riften via Skyrim Unbound. Leave Riften through any gate.

**Expected behavior**
Expected behavior is to be loaded into the open world outside Riften.

**Screenshots**
N/A

**Additional context**
Tried other gates. Same result.

**Comment by PierreDespereaux** [comment]
Fixed in 4.0.0.1
