### ISSUE TITLE
Found some holes in the ground

### ISSUE THREAD

**Issue by Kyle-sys** [PierreDespereaux/Keizaal#103]
**Keizaal version**
4.0.0.

**Describe the bug**
Hopefully title is enough.

**Expected behavior**
For there not to be ground holes if possible.

**Screenshots**
![Skyrim Special Edition 2_12_2021 11_30_18 AM](https://user-images.githubusercontent.com/52866222/107796540-f8c8e680-6d27-11eb-81e0-4004a2ee5fb0.png)
![Skyrim Special Edition 1_31_2021 7_52_53 PM](https://user-images.githubusercontent.com/52866222/106403921-dae1b480-63fe-11eb-8c9e-737991aa2508.png)
![Skyrim Special Edition 1_31_2021 7_53_03 PM](https://user-images.githubusercontent.com/52866222/106403923-dcab7800-63fe-11eb-9df8-e0e3a1858c66.png)
![Skyrim Special Edition 2_12_2021 11_29_18 AM (2)](https://user-images.githubusercontent.com/52866222/107796616-126a2e00-6d28-11eb-8133-175e89f3293a.png)
![Skyrim Special Edition 1_31_2021 7_54_15 PM](https://user-images.githubusercontent.com/52866222/106403932-e03eff00-63fe-11eb-90d7-4498fabef8d3.png)
![Skyrim Special Edition 1_31_2021 7_54_31 PM](https://user-images.githubusercontent.com/52866222/106403936-e208c280-63fe-11eb-819f-ce3abf654d91.png)

**Additional context**
I do have Skyrim Unbound Reborn enabled and placed just above the Keizzal plugins and below the Bugfix Compilation one. Hopefully I've provided enough information. If I do end up finding more ground holes and other things like it, I'll update this post or make another one if this one gets closed or something, maybe idk.

**Comment by PierreDespereaux** [comment]
The holes have not been fixed.

**Comment by PierreDespereaux** [comment]
![image](https://user-images.githubusercontent.com/60482452/107732006-42341a00-6cc5-11eb-9e31-80092a28364f.png)

**Comment by PierreDespereaux** [comment]
I lied it's not fixed

**Comment by PierreDespereaux** [comment]
![image](https://user-images.githubusercontent.com/60482452/108455594-86cb3280-723c-11eb-9105-62644370b93c.png)
![image](https://user-images.githubusercontent.com/60482452/108455695-ad896900-723c-11eb-969a-28c39fb937cf.png)

I swear it's fixed now ~~I hope~~
