### ISSUE TITLE
Can't mount/steal Frost in the mission 'Promises to Keep'

### ISSUE THREAD

**Issue by caddickdaniel** [PierreDespereaux/Keizaal#104]
No crashes or anything to report but I cannot mount a horse? Does the modlist include some requirements for horse riding I'm not aware of similar to some of the guilds? I get the key prompt to mount but it doesn't do anything, both on PC and with a controller. 

No other mods installed aside from Keizaal, amazing mod btw thoroughly enjoying it.

**Comment by PierreDespereaux** [comment]
Are you trying to steal a horse?

**Comment by caddickdaniel** [comment]
> Are you trying to steal a horse?

Technically yes, but its the mission where I need to get Frost back, I've got his papers but I can't mount him, I assume because its listed as 'steal'. Is there a way around this?

**Comment by PierreDespereaux** [comment]
sneak then mount
