### ISSUE TITLE
List of default hotkeys?

### ISSUE THREAD

**Issue by JRice** [PierreDespereaux/Keizaal#105]
I am a non-WASD player. (I know, I know, aberration, but, c'mon, WASD is just plain dumb, the worst position for your hand to hit hotkeys in!) AS such, I remapped the V key in the Skyrim Settings tab.

However, every time I push it, I quaff a potion or use some item. I have NO IDEA what is causing this, nor how to fix it. I looked through the mod configuration tab and nothing mentions it as a hotkey, and I've looked through the installed and enabled mods, but if there's one that does this, it's lost on me. I have NOT enabled any "optional" mods in MO. (I've only just started Keizaal, anyway).

It occurs to me that having a full key map for the default install would be a REALLY helpful addition to the docs. Could such a thing be done, please?

If not, could someone at least point me to where I might fix the 'V' mapping? The game is nigh unplayble for me like this, so it's a blocker for me. :S

Thanks!

**Comment by PierreDespereaux** [comment]
I believe all the custom hoteyes are

iEquip Cycle Right Hand = H
iEquip Cycle Left Hand =G
iEquip Cycle Power = Y
iEquip Cycle Potion = B
iEquip Equip Potion Bomb = U
Call Horse = N
Toggle Compass = X

Disable the mod "Equip Last Item" in MO2. It was not ready for release.
