### ISSUE TITLE
ArteFakes - Unique Artifacts Replacer Recommendation

### ISSUE THREAD

**Issue by daxoon** [PierreDespereaux/Keizaal#109]
**Mod name**
ArteFakes - Unique Artifacts Replacer

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/41254?tab=posts&BH=0

**Why?**
Its a overhaul of the ''less important'' uniquely named weapons in the game. These weapons have unique names but reused appearance and this mod aims to fix it with high quality meshes and textures. A couple of the new weapons overlap with unique unique but we can just lest unique unique overwrite it. 

**Additional context**

**Comment by PierreDespereaux** [comment]
despite not being immediately apparent from the modpage, this mod also changes the stats of a ton of weapons which leads to them becoming overpowered

I am interested in this mod if a straight replacer version is ever made
