### ISSUE TITLE
Forgotten Retex Project

### ISSUE THREAD

**Issue by CANicholson** [PierreDespereaux/Keizaal#11]
**Mod name**
Forgotten Retex Project

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/7849

**Why?**
A great mod to use alongside things like Project Clarity for cleaning up misc. items

**Additional context**
If your wanting to minimize graphics bloat/performance risks maybe give it a miss, but it doesn't look too heavy

**Comment by PierreDespereaux** [comment]
Will be included in Keizaal 3.4.1.
