### ISSUE TITLE
ArranzCNL's Improved Camera

### ISSUE THREAD

**Issue by Ryleyy** [PierreDespereaux/Keizaal#110]
**Mod name**
Immersive Camera

**Mod link**
https://www.reddit.com/r/skyrimmods/comments/cae3x2/mod_improved_camera_beta_3/?sort=new

**Why?**
A 'updated' version of Joy of Perspective. Noticed it's quite configurable and might be a good addition to increase immersion and not ruin anything!

**Additional context**
Camera clips on my current settings due to animations. But I haven't played around with it much yet.

**Comment by PierreDespereaux** [comment]
Is this only available on Google Drive?
