### ISSUE TITLE
Infinite loading screen when talking to Adelaisa Vendicci heading back to Windhelm

### ISSUE THREAD

**Issue by Parygone** [PierreDespereaux/Keizaal#115]
[Save50_B1D80A52_0_41616E746869732044656D6E6576616E6E69_JaphetsFollyWorld_051725_20210209052756_33_1.zip](https://github.com/PierreDespereaux/Keizaal/files/5962336/Save50_B1D80A52_0_41616E746869732044656D6E6576616E6E69_JaphetsFollyWorld_051725_20210209052756_33_1.zip)

Version: Keizaal 4.0.2.5

When telling Adelaisa Vendicci to head back to Windhelm during the quest 'Rise in the East', the game has an infinite loading screen.

1. Talk to Adelaisa Vendicci
2. Choose "I've killed Hadryn"
3. Choose "Let's go"

The game should be load me at the docks where the East Empire Company boat is.

Additional Context: I tried using the coc command to get back to Windhelm but it results in a crash-to-desktop. If you want to the crash report, let me know!

**Comment by PierreDespereaux** [comment]
Yeah throw the crashlog in here.

**Comment by Parygone** [comment]
Hey, just woke up and saw your message. Booted up Skyrim and everything seemed to be fine. Both coc and talking to her seem to be working now. Sorry to have wasted your time.
