### ISSUE TITLE
Werewolf Texture Glitch

### ISSUE THREAD

**Issue by HenryBelgrave** [PierreDespereaux/Keizaal#118]
**Keizaal version**

Keizaal ver. 4.0.4.1

**Describe the bug**

As shown in the attached picture, there's a bug with Sinding's werewolf textures, they do not appear to be right at all. This was taken on the "Ill by moonlight quest". I do not know if this is a general problem with werewolves (although could potentially be) as I have yet to find another werewolf. 

**To reproduce**

Try looking into starting the quest, see his first transformation and then proceed with the quest allying with Sinding in Bloated Man's Grotto to be allowed to clearly see his textures. 

**Expected behavior**

That his textures are shown correctly and that other werewolves in the game don't have this potential issue. 

**Screenshots**

![20210217190509_1](https://user-images.githubusercontent.com/79220573/108249554-80ae5680-7155-11eb-9da4-325f6131ac8d.jpg)

**Additional context**

The mod-list order its as is, nothing modified in it.

**Comment by PierreDespereaux** [comment]
![image](https://user-images.githubusercontent.com/60482452/108298634-49e33b00-716b-11eb-9679-fc6d2958d828.png)
Fixed
