### ISSUE TITLE
Low res textures in near distance

### ISSUE THREAD

**Issue by R4DON1337** [PierreDespereaux/Keizaal#119]
**Keizaal version**
4.0.4.1

**Describe the bug**
Basically textures don't load properly in near distance. I have to get closer to make them load.

**To reproduce**
Steps to reproduce the behavior: just walking around, textures don't load in any open landscape around Skyrim.

**Expected behavior**
Higher resolution textures. Not 4k but at least not that smooth and low res

**Screenshots**
![ScreenShot48](https://user-images.githubusercontent.com/79227298/108266944-0092eb80-716b-11eb-9767-5d9dd7715b30.png)

**Additional context**
Modlist and game are installed on SSD. I haven't added any additional texture mod nor touched load order and LODs

**Comment by PierreDespereaux** [comment]
Are you sure you're on 4.0.4.1? This looks a lot like 4.0.4's LODs.

**Comment by PierreDespereaux** [comment]
![image](https://user-images.githubusercontent.com/60482452/108296626-e7d50680-7167-11eb-9102-019a6f972544.png)

This is what my LODs look like.

**Comment by R4DON1337** [comment]
Just checked and i'm a bonehead. I was sure wabbajack updated the modlist but it actually didn't for some reason. Now i'm on the correct version and the problem is gone. Sorry if i wasted your time, thanks for the help!

**Comment by PierreDespereaux** [comment]
it's all good my dude
