### ISSUE TITLE
Greatsword Sheaths and Scabbards

### ISSUE THREAD

**Issue by HenryBelgrave** [PierreDespereaux/Keizaal#120]
**Mod name**

Greatsword Sheaths and Scabbards Redux SE

**Mod link**

https://www.nexusmods.com/skyrimspecialedition/mods/325/

**Why?**

I think the normal version with vanilla meshes can be used with the new fixed ones in Keizaal to add some consistency to two handed weapons. I mean, even maces and war axes have some sort of holster near the hips.

**Additional context**

Even the ones that do not cover completely the weapon make a difference.

![27178-3-1390601732](https://user-images.githubusercontent.com/79220573/108394607-2c6aab80-7215-11eb-9de2-0ed7999a14a5.jpg)
![27178-4-1359759512](https://user-images.githubusercontent.com/79220573/108394610-2d034200-7215-11eb-9f24-78c30e31d985.jpg)

**Comment by PierreDespereaux** [comment]
Unfortunately this is incompatible with LeanWolf's Better Shaped Weapons.

BSW has its own greatsword sheath solution, but I'm not overly fond of it.
