### ISSUE TITLE
Shields don't show up on back

### ISSUE THREAD

**Issue by Karzyr** [PierreDespereaux/Keizaal#121]
Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Keizaal version**
4.0.4.1

**Describe the bug**
Some shields do not show up on the back. For example, the Nordic, Gilded/Silvered Ebony, Morrowind Glass, Thalmor Glass, Polished Iron shields do not show up on the back once favorited and equipped. These are only some examples that I found, as I'm pretty sure there are more, but the list is huge... 

Initially, I thought it was all non-vanilla shields that didn't work, but it seems that the Bonemold (from Dragonborn) does appear, and the Nordic (which is also from Dragonborn) doesn't.

**To reproduce**
Just favorite and equip a normal Ebony Shield to see it on the back (it works). But if you favorite and equip a Gilded Ebony Shield, it doesn't show up on the back. The same happens to the other shields referenced above.

**Expected behavior**
Expect to see all shields on the back once favorited and equipped.

**Screenshots**
![ScreenShot69](https://user-images.githubusercontent.com/44074202/108425865-fc320580-7232-11eb-9d55-4f0677ea1ce8.png)

![ScreenShot70](https://user-images.githubusercontent.com/44074202/108425867-fd633280-7232-11eb-8de9-154d29b0de63.png)

**Comment by Karzyr** [comment]
The mod does detect the shield, or so it seems.

![ScreenShot71](https://user-images.githubusercontent.com/44074202/108428662-cf7fed00-7236-11eb-880b-b204b5be68b1.png)

**Comment by Karzyr** [comment]
So, I've been doing some digging and I don't quite understand how these things work, but I think I know where the problem is. I'm guessing you'll know better than me where to look and what's wrong. Anyway, here goes:

I decided to open xEdit and run the All Geared Up Meshes Generator script as indicated on the mod's installation tutorial: https://www.youtube.com/watch?v=1nG0kxx15TA

The output folder generated the same files you have inside the Ebony folder in Keizaal Resources/Weapons, except it didn't generate the Ebony Gold version, but it did generate the Ebony Silver one (check images below). I replaced the output with the new files I got, and now the Gold version doesn't show up (not on the hand nor the back), and the Silver only appears on the back (not on the hand). 

*** Test Output Folder ***
![Test](https://user-images.githubusercontent.com/44074202/108440070-63a77f80-724a-11eb-9b07-7d127fcb601a.jpg)


*** Keizaal Resources Folder ***
![KeizaalResources](https://user-images.githubusercontent.com/44074202/108440075-64401600-724a-11eb-86f0-0a1eafa569cc.jpg)

It's obvious that I'm doing something wrong as I have no prior knowledge of using these tools, but I think it is related to those generated meshes. However, as I said in the first post, it's not just the Ebony Shield! Hopefully, this will help you to track down the issue (if you didn't already know what it was :p)!

**Comment by PierreDespereaux** [comment]
![image](https://user-images.githubusercontent.com/60482452/108454575-9c3f5d00-723a-11eb-86c7-789aae8e87ab.png)
![image](https://user-images.githubusercontent.com/60482452/108454612-aa8d7900-723a-11eb-8aff-1233eadb40dd.png)

Fixed
