### ISSUE TITLE
True Teacher Durnehviir Recommendation

### ISSUE THREAD

**Issue by Aosana** [PierreDespereaux/Keizaal#125]
**Mod name**
True Teacher Durnehviir

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/44969

**Why?**
Makes Durnehviir teaching his name to you to be more in line with how other dragons teach you Words of Power in-game, like how Odahviing instantly teaches you Call Dragon and how Paarthurnax instantly teaches you Fire Breath.

**Comment by PierreDespereaux** [comment]
Would this mean a non-Dragonborn could learn a shout?

**Comment by Aosana** [comment]
Hm, yes, I think there would be an issue with Skyrim Unbound - Reborn and this mod if the player chooses to not be Dragonborn.
