### ISSUE TITLE
Invisible Gilded Ebony Helmet

### ISSUE THREAD

**Issue by Karzyr** [PierreDespereaux/Keizaal#128]
**Keizaal version**
4.0.5

**Describe the bug**
The Gilded Ebony Helmet is invisible.

**To reproduce**
Equip a Gilded Ebony Helmet

**Expected behavior**
Non-Invisible Gilded Ebony Helmet :p

**Screenshots**
![ScreenShot57](https://user-images.githubusercontent.com/44074202/108584752-b876f300-733b-11eb-9cfd-9f600e306346.png)

**Comment by Karzyr** [comment]
Race: Redguard (just in case you forget about it)

**Comment by PierreDespereaux** [comment]
This is an incompatibility with Improved Closed-faced Helms. I'm removed that mod. Armor Variants is more important to me and I don't want to try and patch this conflict.
