### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by titaniche** [PierreDespereaux/Keizaal#130]
Hey!
I liked your modlist, but there are some questions.
I want to use another language (not English).
I tried to change ini-files, disable some mods for changing the font, but after that the encoding and the font get confused (squares appear instead of letters). I also tried to remove the _interface_ folder from the Keizaal settings. I tried to install mods that change the interface, but to no avail. Perhaps you can suggest how you might reconfigure the language?
Thank.

**Comment by titaniche** [comment]
Probably everything else it has to do with the encoding. Perhaps it is worth trying to somehow use the program [xTranslator](https://www.nexusmods.com/skyrimspecialedition/mods/134), but I don't understand how you can do this in Mod Organizer 2.

**Comment by PierreDespereaux** [comment]
Translating this modlist into another language is a lot of work, but I'll look into adding xTranslator to the tools.

**Comment by neilrush** [comment]
> Hey!
> I liked your modlist, but there are some questions.
> I want to use another language (not English).
> I tried to change ini-files, disable some mods for changing the font, but after that the encoding and the font get confused (squares appear instead of letters). I also tried to remove the _interface_ folder from the Keizaal settings. I tried to install mods that change the interface, but to no avail. Perhaps you can suggest how you might reconfigure the language?
> Thank.

I found this out the hard way while trying to change the font. 
if you want to disable the installed font you need to delete the font config files out of: `\Keizaal\mods\Keizaal Settings\interface` as they still reference the font files thus creating the squares.

**Comment by TateTaylorUSA** [comment]
Yeah. Changing your language is a lot of work because almost all mods are made in English. Fonts are annoying especially.
