### ISSUE TITLE
Bad texture previewing Vampire Armors

### ISSUE THREAD

**Issue by HenryBelgrave** [PierreDespereaux/Keizaal#131]
**Keizaal version**

4.0.5

**Describe the bug**

A bad texture preview of the Vampire Armor only seen when in the inventory menu

**To reproduce**

Try looking for a vampire, kill them, and when opening the vampire inventory to take their armor, you can see the texture problem

**Screenshots**

![20210222191020_1](https://user-images.githubusercontent.com/79220573/108751259-47edf300-7542-11eb-9e8a-c87eb2791137.jpg)

**Comment by PierreDespereaux** [comment]
hm, odd

**Comment by PierreDespereaux** [comment]
are you playing a male or female?

**Comment by HenryBelgrave** [comment]
I'm playing a female character
