### ISSUE TITLE
Odahviing not attacking during The Fallen quest

### ISSUE THREAD

**Issue by Parygone** [PierreDespereaux/Keizaal#133]
**Keizaal version**
4.0.5

**Describe the bug**
When I use the Call Dragon shout on the Dragonsreach great porch for the The Fallen quest, Odahviing just flies past & doesn't attack. Meaning I can't trap him and advance the quest.

**To reproduce**
Steps to reproduce the behaviour:
1. Use 'Call Dragon' shout to call Odahviing on the Dragonsreach great porch.
2. Wait for Odahviing to fly past.

**Expected behaviour**
Odahviing should start attacking, first by swooping down and picking up the Whiterun guard.

[Autosave1_B1D80A52_0_41616E746869732044656D6E6576616E6E69_WhiterunDragonsreachWorld_061314_20210224001002_34_1.zip](https://github.com/PierreDespereaux/Keizaal/files/6033585/Autosave1_B1D80A52_0_41616E746869732044656D6E6576616E6E69_WhiterunDragonsreachWorld_061314_20210224001002_34_1.zip)

**Comment by Parygone** [comment]
And yes, I did try to use the Dragonrend shout. But that didn't work ;/

**Comment by PierreDespereaux** [comment]
This is a Vanilla bug
![image](https://user-images.githubusercontent.com/60482452/109253619-29942b80-77be-11eb-9b83-5a5816ba670a.png)
