### ISSUE TITLE
Bad positioning of an asset at the Shrine of Peryite

### ISSUE THREAD

**Issue by HenryBelgrave** [PierreDespereaux/Keizaal#134]
**Keizaal version**

4.0.5

**Describe the bug**

An eagle's nest misplaced in the air at the Shrine of Peryite in the Reach. 

**To reproduce**

Go there, and you'll see it cleary in the sky above of, what I suppose, should be the original tree it were to stand.

**Screenshots**
![20210224135907_1](https://user-images.githubusercontent.com/79220573/109004805-86ea8880-76a9-11eb-865b-78e43b85fa80.jpg)
![20210224135922_1](https://user-images.githubusercontent.com/79220573/109004812-881bb580-76a9-11eb-9c9f-51056a576e77.jpg)

**Comment by PierreDespereaux** [comment]
lul how did this happen
I'll fix it.
