### ISSUE TITLE
White River Watch - Outside Area Failed to Load

### ISSUE THREAD

**Issue by SakiMcGee** [PierreDespereaux/Keizaal#135]
**Keizaal version**
4.0.5

**Describe the bug**
Playing through White River Watch, I picked the expert lock on the cell gate just to the right of the main area. I proceeded forward to an exit out to Skyrim, and as soon as the outdoor level loaded, many issues appeared. Textures were missing from the world and characters, I was unable to access any UI or menu elements despite the game still pausing on key press. My follower continued moving forward and fighting, but nearly every other system was failing. I turned and went back the way I had come, and upon loading the interior map, everything was in working order again...except I was dropped behind the warp point, in the empty hallway beyond the outside map's load trigger. 

The initial incident of the outside map failing to load completely hasn't happened again, but in running back and forth through the triggers, it does now consistently drop me back on the wrong side of the indoor trigger. It also just started doing random things, as one time I passed through the load point, the game decided to spawn my horse there with me?

**To reproduce**
I have been unable to reproduce the load failure I first experienced, but the oddities with that specific load point are pretty consistent. There is also a split second, when going back into the dungeon, that the screen flashes with the untextured version I saw initially. It does not last though, and is back to normal once inside.

**Expected behavior**
I expected all game systems and functions to load properly beyond that warp point, and expected to be placed in the same location when I passed through it once again.

**Screenshots**
https://imgur.com/a/8RZSbAd

**Additional context**
None that I can think of.

**Comment by PierreDespereaux** [comment]
Provide me with your save files.

**Comment by PierreDespereaux** [comment]
Cannot replicate. I may be able to reopen this issue if you provide me with a savegame.
