### ISSUE TITLE
Surprise Small Critters Recommendation

### ISSUE THREAD

**Issue by Aosana** [PierreDespereaux/Keizaal#137]
**Mod name**
Surprise Small Critters

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/46428

**Why?**
This mod adds lore-friendly tiny enemies to some dungeons for the player to encounter and scream in terror at!

**Comment by PierreDespereaux** [comment]
I dunno if I'm brave enough for this mod

**Comment by PierreDespereaux** [comment]
oh hey I know the guy who made it

**Comment by PierreDespereaux** [comment]
I'm not brave enough.

**Comment by Aosana** [comment]
Coward.
