### ISSUE TITLE
FK Diverse Racial Skeletons - Aetherius.esp errors

### ISSUE THREAD

**Issue by Codygits** [PierreDespereaux/Keizaal#145]
**Keizaal version**
4.0.8.2

**Describe the bug**
Khajjit's and Argonian's + thier vampire versions are missing their racial buffs.

**To reproduce**
Start a new game and choose either Khajjit or Argonian, they will be missing their racial buffs.

**Expected behavior**
Khajiit should have Lunar Blessing and Argonians should have Histskin in their active magic effetcs.

**Screenshots**
![fk1](https://user-images.githubusercontent.com/20106025/111626991-95b1f000-87bc-11eb-9be8-648cb6d17a67.PNG)
![fk2](https://user-images.githubusercontent.com/20106025/111626998-98ace080-87bc-11eb-8f2d-80e5e2fc4e37.PNG)

**Comment by PierreDespereaux** [comment]
Fixed in Keizaal 4.0.9
