### ISSUE TITLE
Werewolf Texture Bug

### ISSUE THREAD

**Issue by Codygits** [PierreDespereaux/Keizaal#146]
**Keizaal version**
4.0.8.2

**Describe the bug**
Werewolves that spawn in the marsh have transparent textures / see through patches. I believe its the same bug as in issue #118.

**To reproduce**
Start a new game and fast travel to the Solitude docks and walk directly into the marsh, you encounter a pack of werewolves that will have messed up textures.

**Expected behavior**
Not see through textures.

**Screenshots**
![enb2021_3_18_07_46_59](https://user-images.githubusercontent.com/20106025/111628886-b3805480-87be-11eb-9876-d0cef3b0d62d.jpg)

**Comment by PierreDespereaux** [comment]
Fixed in Keizaal 4.0.9
