### ISSUE TITLE
The Companions main questline won't advance to Proving Honour

### ISSUE THREAD

**Issue by Parygone** [PierreDespereaux/Keizaal#147]
Keizaal Version: 4.1.1 & 4.1.2

I can not advance the companions questline. I have done about 12 radiant quests now and I still haven't gotten the Proving Honour quest to start. I tried using console commands to start the quest myself, but that's not working. You removed the mod that affects how many radiant quests you need to do before doing the main missions and that's what's most likely causing the issue. I've posted two times in the Keizaal support channel for help but you haven't responded to me so I'm posting it on GitHub.

[Save77_B1D80A52_0_41616E746869732044656D6E6576616E6E69_WhiterunJorrvaskr_071434_20210414051934_36_1.zip](https://github.com/PierreDespereaux/Keizaal/files/6328095/Save77_B1D80A52_0_41616E746869732044656D6E6576616E6E69_WhiterunJorrvaskr_071434_20210414051934_36_1.zip)

**Comment by PierreDespereaux** [comment]
I cannot replicate this issue on a new save, but I have no idea why your save in particular appears to be having this issue.

**Comment by Parygone** [comment]
Ok, thank you for the response. Let me know of any updates to solving this.
