### ISSUE TITLE
Favorite Misc Items Recommendation

### ISSUE THREAD

**Issue by Aosana** [PierreDespereaux/Keizaal#2]
**Mod name**
Favorite Misc Items

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/42750

**Why?**
It will allow players to favorite commonly used but unfavoritable items such as torches, or any other important or usable miscellaneous items added by mods.

**Comment by PierreDespereaux** [comment]
This mod has been accepted and will be included in Keizaal 3.4.0.
