### ISSUE TITLE
HEY PIERRE ACTUALLY READ THIS ISSUE INSTEAD OF AUTOMATICALLY CLOSING IT

### ISSUE THREAD

**Issue by MediumLowQuality** [PierreDespereaux/Keizaal#21]
**Mod name**
Difficulty Balance

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/35767

**Why?**
It is a good mod.

**Comment by PierreDespereaux** [comment]
ok

**Comment by PierreDespereaux** [comment]
Will be included in the next version of Keizaal.
