### ISSUE TITLE
Forceful Tongue - Shouts Overhaul - Making the Dragonborn cool again

### ISSUE THREAD

**Issue by CANicholson** [PierreDespereaux/Keizaal#22]
**Mod name**
Forceful Tongue - Shouts Overhaul

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/36276

**Why?**
Discussing potential Shout overhauls in the discord and this is the most V+ on the market so far

**Additional context**
Might be too stronk

**Comment by PierreDespereaux** [comment]
There are balancing concerns with this mod.
