### ISSUE TITLE
Forceful Tongue - Dragonborn Perk Tree - Making the Dragonborn cool again

### ISSUE THREAD

**Issue by CANicholson** [PierreDespereaux/Keizaal#23]
**Mod name**
Forceful Tongue - Dragonborn Perk Tree

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/41950

**Why?**
A slick implementation that lets playing as the Dragonborn actually unique without much overhead like config abilities and without destroying game balance

**Additional context**
*cries in Survival w/ no fast travel*

**Comment by PierreDespereaux** [comment]
There are balancing concerns with this mod. However, I really like the idea of it. I may look into making my own version in the future.
