### ISSUE TITLE
Dovahkiin's Vault SSE- Making the Dragonborn cool again

### ISSUE THREAD

**Issue by CANicholson** [PierreDespereaux/Keizaal#24]
**Mod name**
Dovahkiin's Vault SSE

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/42237

**Why?**
For every collector of rare curios, a slick fit that makes the Throat of the World a bit more interesting that makes sense as opposed to a small hut that somehow has space for all this. Also to stop eventual requests for LotD.

**Additional context**
*cries in Survival w/ no Fast Travel*

**Comment by PierreDespereaux** [comment]
This mod is _almost_ what I want. However, locking it so far behind the main quest is very problematic.
