### ISSUE TITLE
Skyrim Sizes

### ISSUE THREAD

**Issue by Parygone** [PierreDespereaux/Keizaal#25]
**Mod name**
Skyrim Sizes

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/587

**Why?**
1. It is lightweight (25-27kb)
2. It is immersive (Files section has a 'Lore' option)

**Additional context**
Pictures and additional context on mod description page

**Comment by PierreDespereaux** [comment]
I am content with the vanilla sizes.
