### ISSUE TITLE
Relationship Dialouge Overhaul

### ISSUE THREAD

**Issue by PierreDespereaux** [PierreDespereaux/Keizaal#26]
**Mod name**
Relationship Dialouge Overhaul

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/1187

**Why?**
I mainly want to add RDO to make vanilla followers a bit more interesting. As-is they're pretty mute when on the road, but I'd like them to be a bit more lively. In addition it will generally just make idle dialogue more interesting.

**Additional context**

**Comment by spooknik** [comment]
Hello, sorry for commenting on a close issue. 

I saw that you closed this, but I cannot seem to find RDO in the current version of the modpack? I tried to add RDO manually, but the game does not start; the .exe runs for a few seconds and then it goes back MO2.
