### ISSUE TITLE
Overly shadowed area when not using ENB in area around Swindlers Den

### ISSUE THREAD

**Issue by CANicholson** [PierreDespereaux/Keizaal#28]
[Saves.zip](https://github.com/PierreDespereaux/Keizaal/files/5684243/Saves.zip)

[**Keizaal] version**
3.4.2

**Describe the bug**
With no ENB, in outdoor areas are overly dark

**To reproduce**
Around Swindlers Den, disable your ENB during later hours. 

**Expected behavior**
A clearer late night sky

**Screenshots**
Both of these images were taken at 6:48PM in-game time
Without any ENB
![ScreenShot4](https://user-images.githubusercontent.com/11443039/102003870-20d5a280-3d03-11eb-94a5-e3af61624ae8.png)
With The Truth ENB
![ScreenShot5](https://user-images.githubusercontent.com/11443039/102003878-2b903780-3d03-11eb-8fad-83c061400f23.png)

**Comment by PierreDespereaux** [comment]
Over two weeks without any further reports of the bug. Assumed resolved.
