### ISSUE TITLE
Remember Lockpick Angle - Updated Recommendation

### ISSUE THREAD

**Issue by Aosana** [PierreDespereaux/Keizaal#30]
**Mod name**
Remember Lockpick Angle - Updated

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/26838

**Why?**
This mod is catered very well to thief builds, but I honestly think it helps everyone who doesn't use the Mysticism lock spells. It's another SKSE plug-in, so no slot needed!

**Comment by PierreDespereaux** [comment]
I find this too cheaty.
