### ISSUE TITLE
Enemy (R)Evolution of Skyrim - EEOS - Spell Perk Items Distributor Addon Recommendation

### ISSUE THREAD

**Issue by Aosana** [PierreDespereaux/Keizaal#32]
**Mod name**
Enemy (R)Evolution of Skyrim - EEOS - Spell Perk Items Distributor Addon

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/37228

**Why?**
This mod allows NPCs to use Mysticism spells. As such, it makes the game much more difficult, so balance may be an issue. 

**Additional context**
This mod requires Spell Perk Item Distributor (https://www.nexusmods.com/skyrimspecialedition/mods/36869). Neither mods take a slot in your load order, and they can be added or removed whenever without issue.

**Comment by PierreDespereaux** [comment]
There are a lot of spells in Mysticism that are not balanced for NPC use. The only way that Mysticism spells will be distributed in Keizaal is if Simon or I does it manually.
