### ISSUE TITLE
Iron Dusk's Laboratory (WIP Mod Collection) Recommendation 

### ISSUE THREAD

**Issue by Aosana** [PierreDespereaux/Keizaal#33]
**Mod name**
Iron Dusk's Laboratory (WIP Mod Collection); more specifically, the Saddlebags module. 

**Mod link**
https://www.nexusmods.com/skyrim/mods/91395

**Why?**
With the recent inclusion of Better Horses, I thought it'd be good for horses to be given further use with this mod. There are not many inventory-related mods in Keizaal, and so this addition makes Survival Mode players and hoarders (two descriptors I myself fall under) have an easier way to manage carry weight that still must be earned.

**Additional context**
The mod is from Oldrim, so you'll need to do some boring converting work. It also adds a horse whistle! You can get rid of it if you want, though.

**Comment by PierreDespereaux** [comment]
I'd like something a little different out of a saddlebag mod, but if none can be found I think this is probably an okay inclusion.

**Comment by PierreDespereaux** [comment]
Part of me worries that it will make inventory space trivial, but at the same time horses don't come cheap.

Hmm. I'll think on it some more.

**Comment by PierreDespereaux** [comment]
Modified storage space to be 100 instead of 500 and removed the horse whistle power (Simple Horse's is better)
