### ISSUE TITLE
Ghosts of Deathbells

### ISSUE THREAD

**Issue by ShapeZed** [PierreDespereaux/Keizaal#34]
@**Mod name**
Ghosts of the Deathbells

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/20814

**Why?**
It should be added for extra lore-friendly depth to the general experience by adding a little bit that goes a long way.

**Additional context**
https://youtu.be/i2HemwKudAs

**Comment by Aosana** [comment]
This was added in Keizaal 3.4.1.

**Comment by PierreDespereaux** [comment]
As @Aosana said, Ghosts of the Deathbells is already in Keizaal.
