### ISSUE TITLE
Unique Dragon Aspect

### ISSUE THREAD

**Issue by Parygone** [PierreDespereaux/Keizaal#35]
Unique Dragon Aspect

https://www.nexusmods.com/skyrimspecialedition/mods/18583

Like the title says, it makes the Dragon Aspect shout more unique for the player and Miraak. A little mod that is immersive and makes the shout feel a lot more special.

Screenshots on mod page. (My prefs are Whitegold for the Dragonborn and Venom for Miraak.

**Comment by PierreDespereaux** [comment]
I really like the look of this mod! I'll definitely be checking this out for Keizaal 3.4.4.

**Comment by PierreDespereaux** [comment]
Will be included in Keizaal 3.4.4
