### ISSUE TITLE
Scarecrows of Skyrim Recommendation

### ISSUE THREAD

**Issue by Aosana** [PierreDespereaux/Keizaal#37]
**Mod name**
Scarecrows of Skyrim 

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/39575

**Why?**
Cute lil' scarecrows! It's another tiny esl-flagged mod that adds just a little bit more depth to the game.

**Additional context**
![image](https://user-images.githubusercontent.com/75114560/102350594-c3438f00-3f6a-11eb-86b8-3d73bd34bf44.png)
I sure hope that image thing works

**Comment by PierreDespereaux** [comment]
I really love the look of this

**Comment by PierreDespereaux** [comment]
Will be included in Keizaal 3.4.4
