### ISSUE TITLE
Improved Imperial Helmet (Closed)

### ISSUE THREAD

**Issue by PierreDespereaux** [PierreDespereaux/Keizaal#39]
**Mod name**
Improved Imperial Helmet (Closed)

**Mod link**
https://www.nexusmods.com/skyrim/mods/93366?tab=description

**Why?**
Just a nice overhaul of the closed Imperial Helmet.

**Additional context**

![](https://staticdelivery.nexusmods.com/mods/110/images/93366/93366-1541287209-733755674.png)

**Comment by Aosana** [comment]
This looks really cool!

**Comment by PierreDespereaux** [comment]
Strange conflict with CC's Daedric Mail. Rejected or now, but I may revist this mod in the future to figure out what is wrong.
