### ISSUE TITLE
kitties!!!! A Cat's Life

### ISSUE THREAD

**Issue by PedroC47** [PierreDespereaux/Keizaal#4]
**Mod name**
A Cat's Life

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/37250

**Why?**
To make the world a little bit more immersive, and it's fair to cats since dogs exist in the game. 

**Additional context**
https://www.youtube.com/watch?v=2Gx8QWvk7lc

**Comment by PierreDespereaux** [comment]
There's something about this mod that doesn't feel right. Perhaps it's the pet shops, they feel a little weird in the fantasy world. I may look elsewhere into adding cats in a similar way to how dogs are integrated into Vanilla.
