### ISSUE TITLE
Nordic Carved Clipping Fix Recommendation

### ISSUE THREAD

**Issue by Aosana** [PierreDespereaux/Keizaal#40]
**Mod name**
Nordic Carved Clipping Fix

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/43444/

**Why?**
It's another simple mesh fix/edit in the same vein as mods already included in Keizaal such as Ebony Armor Male Neck Gap Fix.

**Comment by PierreDespereaux** [comment]
XP32 already has a version of this fix.

**Comment by PierreDespereaux** [comment]
ended up including it anyway because "why not?"
