### ISSUE TITLE
Enhanced Reanimation Recommendation

### ISSUE THREAD

**Issue by Aosana** [PierreDespereaux/Keizaal#42]
**Mod name**
Enhanced Reanimation

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/43500

**Why?**
Just another SKSE plug-in that fixes things relating to reanimation.

**Additional context**
![image](https://user-images.githubusercontent.com/75114560/102713308-06647180-428d-11eb-8bc8-ae4406094b29.png)

**Comment by PierreDespereaux** [comment]
Will be included in Keizaal 3.4.0.
