### ISSUE TITLE
AGO and AllGUD Bow Dupe Bug Report

### ISSUE THREAD

**Issue by Aosana** [PierreDespereaux/Keizaal#43]
**Keizaal version**
Keizaal 3.4.4

**Describe the bug**
When the player character draws a bow that is equipped on their back from AllGUD, they hold a bow while simultaneously still having the same bow on their back.

**To reproduce**
Draw a bow in third-person while it is on your back.

**Expected behavior**
The bow should be removed from your back and placed firmly in your grasp.

**Screenshots**
![489830_20201220115746_1](https://user-images.githubusercontent.com/75114560/102720635-2579f800-42bb-11eb-9698-5db371023d14.png)
![489830_20201220115759_1](https://user-images.githubusercontent.com/75114560/102720638-2b6fd900-42bb-11eb-87f9-9262ee8992bb.png)

**Comment by PierreDespereaux** [comment]
Should be fixed in Keizaal 3.4.5, will be released on Christmas Eve.
