### ISSUE TITLE
Skyrim Fixes Collection

### ISSUE THREAD

**Issue by KaptainCnuckz** [PierreDespereaux/Keizaal#44]
**Mod name**
Skyrim Fixes Collection

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/38314

**Why?**
Has various minor fixes to meshes, placed objects, and gaps in areas.

**Additional context**
You could opt for not using the mod's plugin, and only use the various fixed meshes. If you happen to have anything that edits placed objects in that same area it would avoid conflicts.

**Comment by MediumLowQuality** [comment]
>milkjam

**Comment by PierreDespereaux** [comment]
Rejected on account of milkman
