### ISSUE TITLE
Skyrim Landscape and Water Fixes

### ISSUE THREAD

**Issue by KaptainCnuckz** [PierreDespereaux/Keizaal#45]
**Mod name**
Skyrim Landscape and Water Fixes

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/26138

**Why?**
Contains various fixes to gaps in the landscape. It also adds ownership to crops, and lets you ask to harvest them.

**Additional context**
Admittedly the crop ownership is feature creep. It's not as annoying as you'd think, in practice. Usually pretty quick finding a farmer living there. Also helps how you can walk off with the crops after if you want them.

**Comment by PierreDespereaux** [comment]
You know I'm going to have to check this out. Tbh crop ownership sounds like a compelling feature.

**Comment by PierreDespereaux** [comment]
Will be added in Keizaal 3.4.5. I liked the crop ownership changes.
