### ISSUE TITLE
Smooth Windhelm Ground Meshes

### ISSUE THREAD

**Issue by KaptainCnuckz** [PierreDespereaux/Keizaal#46]
**Mod name**
Smooth Windhelm Ground Meshes

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/42746

**Why?**
It smooths out Windhelm's ground meshes, making them look much nicer.

**Additional context**
No plugin and only has altered meshes, so most likely compatible with any city overhauls that edit Windhelm.

Vanilla:
![image](https://user-images.githubusercontent.com/76413382/102732916-e4f59b00-4309-11eb-8493-1b599d2e7e12.png)
With Mod:
![image](https://user-images.githubusercontent.com/76413382/102732956-fccd1f00-4309-11eb-87e3-a318e855d63a.png)

**Comment by PierreDespereaux** [comment]
as beautiful as this mod is I've had strange glitches with it where the ground would disappear and everyone would be levitating. It may be an OCS issue.
