### ISSUE TITLE
Dawnguard Arsenal Recommendation

### ISSUE THREAD

**Issue by Parygone** [PierreDespereaux/Keizaal#47]
Dawnguard Arsenal

https://www.nexusmods.com/skyrimspecialedition/mods/25094

Adds in new weapons (bladed weapons, two-handed axe & warhammer) & sun damage spells for the Dawnguard faction. Also can craft weapons & improves the weapons' special melee damage to vampires.

Additional context & screenshots can be found on the mod page.

**Comment by PierreDespereaux** [comment]
This mod has some incompatibilities with Mysticism. I may look into ripping just the new weapons out.
