### ISSUE TITLE
Bogmorts just be vibing (not aggressive)

### ISSUE THREAD

**Issue by Milutz420** [PierreDespereaux/Keizaal#48]
**Keizaal version**
3.4.4

**Describe the bug**
Bogmorts don't become aggressive when approached or attacked.

**To reproduce**
Steps to reproduce the behavior: walz into Morthal swamps and find these creepy mudmen just vibing

**Expected behavior**
I guess they should attack me and be a threat?

[Saves.zip](https://github.com/PierreDespereaux/Keizaal/files/5725668/Saves.zip)

**Comment by PierreDespereaux** [comment]
I believe this was a strange fluke. I recommend traveling away from Morthal and then return at a later date. If the Bogmorts are still being weird we can investigate further. I was able to find hostile Mudmen further into the swamps for example.
