### ISSUE TITLE
Loki's Wade in Water Recommendation 

### ISSUE THREAD

**Issue by Aosana** [PierreDespereaux/Keizaal#5]
**Mod name**
Loki's Wade in Water

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/42854

**Why?**
This mod adds a small amount of immersion by slowing down players and NPCs that are immersed in water. 

**Additional context**
Here's a video demonstration: https://youtu.be/6YweJd40A4U

**Comment by PierreDespereaux** [comment]
This mod has been accepted for inclusion and will be added in Keizaal 3.4.0.
