### ISSUE TITLE
Complete Widescreen Fix

### ISSUE THREAD

**Issue by Atokata** [PierreDespereaux/Keizaal#53]
**Mod name**
Complete Widescreen Fix

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/1778

**Why?**
It's a mod that makes Skyrim compatible with Ultrawide resolutions.

**Additional context**
There are a few extra files to make the mod compatible with Extended UI, SKYUI, Wider MCM, etc.

**Comment by PierreDespereaux** [comment]
I'll add this to the optional section, but I'm not configuring it at all and I won't support it. I just don't have an ulrawide to test these features on.

**Comment by PierreDespereaux** [comment]
Turns out there are too many files to simply add the the optional section.
