### ISSUE TITLE
NPCs not giving skill up on quest completion

### ISSUE THREAD

**Issue by Raiuki** [PierreDespereaux/Keizaal#55]
**Keizaal version**
3.3.4.3

**Describe the bug**
I've noticed a bug not sure what could be causing it though. For quests where the reward is a skill point increase I.E. Getting Amren's sword/ The Mammoth Tusk for Ysolda, the related skills aren't going up when I complete the quest

**To reproduce**
Accept quest from Ysolda or Amren, though Ysolda would be simpler.
spawn in mammoth tusk.
give it to her.

**Expected behavior**
Should be giving a skill up at the end of the quest

**Additional context**

**Comment by PierreDespereaux** [comment]
I was not able to reproduce this issue on 3.4.0 RC2.
