### ISSUE TITLE
Casual Skyrim Recommendation 

### ISSUE THREAD

**Issue by Aosana** [PierreDespereaux/Keizaal#56]
**Mod name**
Casual Skyrim 

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/16575

**Why?**
It prevents NPCs from stopping their work to talk to you. They can multitask!

**Comment by PierreDespereaux** [comment]
I think vanilla Skyrm handles "multitasking" fine. I'm not really into those sleeptalkers lmao
