### ISSUE TITLE
Cooleoj's Revisited Series

### ISSUE THREAD

**Issue by PierreDespereaux** [PierreDespereaux/Keizaal#57]
**Mod name**
Cooleoj's Revisited Series

**Mod link**
https://www.nexusmods.com/users/920551?tab=user+files

**Why?**
Cooleoj has been remaking some vanilla dungeons and added some new paths and puzzles to make them a bit less linear and more interesting while still retaining the look and feel of the dungeon.

**Additional context**
ELFX appears to have issues, even with the provided patches.

This recommendation is for the entire series, but not all may be accepted.

**Comment by Aosana** [comment]
I personally use all of these mods, and I think they're wonderful. :)
