### ISSUE TITLE
Swamp fungal pod by Mari Recommendation

### ISSUE THREAD

**Issue by Aosana** [PierreDespereaux/Keizaal#63]
**Mod name**
Swamp fungal pod by Mari

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/44017

**Why?**
Another plant retexture from Mari! :D

**Additional context**
![image](https://user-images.githubusercontent.com/75114560/103704669-46a33f80-4f6f-11eb-87cf-8c4345ca3e42.png)
Vanilla and modded comparison.

**Comment by PierreDespereaux** [comment]
Already covered by Renthal's Fungal Swap Pods.
https://www.nexusmods.com/skyrim/mods/80722
