### ISSUE TITLE
The Woodcutter's wife ported and fixed Recommendation

### ISSUE THREAD

**Issue by Aosana** [PierreDespereaux/Keizaal#64]
**Mod name**
The Woodcutter's wife ported and fixed

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/44020

**Why?**
Adds another lore-friendly ghost NPC to Falkreath Hold. I don't know if it will at all conflict with Falkreath Hauntings, or if you feel like there are already enough horror-themed NPCs in that area thanks to that mod.

**Additional context**
It sounds like defeating her doesn't actually get rid of her as she respawns nightly? Not sure how that lines up with established lore about ghosts in The Elder Scrolls, or if it fits the gameplay of Skyrim itself, as you can defeat ghosts that do not reappear afterward.

**Comment by PierreDespereaux** [comment]
I find the audio of her weeping to be too low quality. Falkreath Hauntings makes the hold creepy enough anyway,
