### ISSUE TITLE
Destroy the Thieves Guild Recommendation

### ISSUE THREAD

**Issue by Parygone** [PierreDespereaux/Keizaal#66]
Destroy the Thieves Guild

https://www.nexusmods.com/skyrimspecialedition/mods/43244

It can finally give players the option to get rid of the people who are leeching off the citizens of Riften while also getting some the guild quest rewards.

Additional context & screenshots on mod page.

**Comment by PierreDespereaux** [comment]
I like the idea of dismantling the Thieves Guild, but murdering everyone in the Ragged Flagon fells wrong to me for some reason.
