### ISSUE TITLE
Trua - Minimalistic Faiths of Skyrim

### ISSUE THREAD

**Issue by Atokata** [PierreDespereaux/Keizaal#67]
**Mod name**
Trua - Minimalistic Faiths of Skyrim

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/32549

**Why?**
It's an immersive mod that adds minimalistic faiths to not be intrusive but offer a bonus to role-play worshiping a specific God.

**Comment by MediumLowQuality** [comment]
lmao
