### ISSUE TITLE
Keizaal 3.4.1 Crash To Desktop

### ISSUE THREAD

**Issue by Parygone** [PierreDespereaux/Keizaal#68]
[Crash_2021_1_9_11-8-47.txt](https://github.com/PierreDespereaux/Keizaal/files/5789899/Crash_2021_1_9_11-8-47.txt)
[Quicksave0_B1D80A52_0_41616E746869732044656D6E6576616E6E69_FrostflowLighthouse_041212_20210108084332_32_1.zip](https://github.com/PierreDespereaux/Keizaal/files/5789902/Quicksave0_B1D80A52_0_41616E746869732044656D6E6576616E6E69_FrostflowLighthouse_041212_20210108084332_32_1.zip)

Keizaal Version: 3.4.1

Bug Description:
Crash to desktop after loading save.

Steps to reproduce the behaviour:
1. Unzip my save into your SSE Saves folder in your Documents.
2. Load my save in Keizaal 3.4.1.

Expected Behaviour:
Should load my save, saying as how the 3.4.1 release log said that this new update was save game compatible,

**Comment by PierreDespereaux** [comment]
I'll check this out ASAP. Looks like Immersive Patrols is being fucky.

Try loading some earlier saves.

**Comment by Parygone** [comment]
Yeah I did that before. But I will try it again.

Two minor things to note,

1. You have a patch for Survival Mode - Modest Elderly, but it doesn't seem the Modest Elderly is even downloaded or installed.
![image](https://user-images.githubusercontent.com/69613317/104078601-1b706700-5273-11eb-9b34-d900e7d74ad7.png)

2. The Unofficial Skyrim Creation Club Content Patch requires reinstalling but you've removed the mod from the Downloads folder so I have to reinstall it from Nexus.
![image](https://user-images.githubusercontent.com/69613317/104078916-9dad5b00-5274-11eb-9981-dce81ab0d10d.png)

**Comment by Parygone** [comment]
Okay, so those two minor issues I fixed.

1. Modest Elderly was under Hidden files.
2. Mod Organiser 2 couldn't find the Unofficial Skyrim Creation Club Content Patch in the Downloads folder.

Sorry for any confusion.

**Comment by PierreDespereaux** [comment]
Modest Elder *should* have been removed.

I'll fix the CC patch too in the hotfix.

**Comment by PierreDespereaux** [comment]
The CC patch seems to be working correctly for me for some reason.

**Comment by Parygone** [comment]
Yeah, I tried reinstalling Modest Elderly after I couldn't find it and it said it was already downloaded so I was very confused lol.

**Comment by PierreDespereaux** [comment]
Okay, good news, I've fixed your CTD issue. I'm going to being uploading 4.3.1.1 now.
