### ISSUE TITLE
Cannot Claim Bleak Falls Tower

### ISSUE THREAD

**Issue by PierreDespereaux** [PierreDespereaux/Keizaal#71]
**Keizaal version**
3.5.0

**Describe the bug**
Despite there being no enemies in sight, Bleak Falls Tower cannot be claimed with Lawbringer.

**To reproduce**
Clear out Bleak Falls Tower and attempt to claim it.

**Expected behavior**
Claim Bleak Falls Tower for the faction of your choice.

**Screenshots**
![ScreenShot1](https://user-images.githubusercontent.com/60482452/104547066-9fbc4480-55fb-11eb-854a-a46fa2ca953b.png)

**Additional context**
I will check with EpicCrab to see if this is a known issue, if not I will attempt to replicate it on a Vanilla game.

**Comment by LuisAverhoff** [comment]
Had this same problem. Was able to claim it after clearing bleak falls barrow. Note, I do not know if it was truly because I cleared it or that enough time had passed.

**Comment by PierreDespereaux** [comment]
I believe this has been fixed. Will reopen if I am incorrect.

**Comment by Gamzy202** [comment]
has therir been a fix cause im trying to claim rift tower and same problem aside form only friendly characters being their
