### ISSUE TITLE
Orcish Light Armor Neck Gap

### ISSUE THREAD

**Issue by jeremyeng** [PierreDespereaux/Keizaal#72]
**Keizaal version**
3.4.2

**Describe the bug**
Gap between the neck and head when wearing the female version of the Orcish Light Armor

**To reproduce**
- Create female character
- Equip Orcish Light Armor

**Expected behavior**
There shouldn't be a gap.

**Screenshots**
![20210114181838_1](https://user-images.githubusercontent.com/18728526/104667622-773c5500-56a4-11eb-83c7-4cf477696a07.jpg)

**Comment by PierreDespereaux** [comment]
I can't fix mesh issues, but I'll keep it open just for reference.

**Comment by PierreDespereaux** [comment]
I've replaced this mesh with a different mesh that does not have the clipping issue.
