### ISSUE TITLE
Swinging weapon arm texture missing

### ISSUE THREAD

**Issue by Pixelmation** [PierreDespereaux/Keizaal#75]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Keizaal version**
3.5.1

**Describe the bug**
A purple texture is shown on the arm of the character when swinging a dagger with ancient Dark Brotherhood armor equipped

**To reproduce**
swing a dagger with ancient Dark Brotherhood armor equipped

**Expected behavior**
the regular texture to be shown

**Screenshots**
![image](https://user-images.githubusercontent.com/33030639/104859532-14d99380-58f4-11eb-9425-91db998b8fe7.png)

**Comment by PierreDespereaux** [comment]
Fixed for next version.
