### ISSUE TITLE
Couple of Morthal trees that you can become trapped in

### ISSUE THREAD

**Issue by Kyle-sys** [PierreDespereaux/Keizaal#77]
Idk for sure if it is a bug or not. I am on the latest version of Keziaal and only enabled Skyrim Unbound Reborn. Here is a couple of screenshots and a video:
Screenshots:
![Skyrim Special Edition 1_18_2021 9_28_03 PM](https://user-images.githubusercontent.com/52866222/104980725-424a3e00-59d5-11eb-8c7d-d884761c7347.png)

![Skyrim Special Edition 1_18_2021 9_48_33 PM](https://user-images.githubusercontent.com/52866222/104981755-395a6c00-59d7-11eb-8020-24925e7c25f3.png)

Video:
https://youtu.be/GdQ08LPgwiQ

**Comment by PierreDespereaux** [comment]
I will relay this to the author, but I will not personally fix it.

**Comment by PierreDespereaux** [comment]
actually I keep this open for reference

**Comment by PierreDespereaux** [comment]
The mod that this tree is from is no longer in the modlist.
