### ISSUE TITLE
Water seam near the Guardian Stones

### ISSUE THREAD

**Issue by Kyle-sys** [PierreDespereaux/Keizaal#78]
**Keizaal version**
Lastest version. Version 3.5.1.2

**Describe the bug**
Hopefully title is enough

**To reproduce**
Look overhead from the Guardian Stones

**Expected behavior**
For there to not be a water seam if possible.

**Screenshots**
![Skyrim Special Edition 1_19_2021 9_25_20 AM](https://user-images.githubusercontent.com/52866222/105047493-6723cd00-5a38-11eb-8f91-b6b1c50b7a8c.png)

**Additional context**
Idk if I can highlight the water info via console, just says activator or something.

**Comment by PierreDespereaux** [comment]
Fixed.
![ScreenShot31](https://user-images.githubusercontent.com/60482452/105440321-63f53080-5c34-11eb-8f85-49e6178d7590.png)
