### ISSUE TITLE
Female altmer hair 16 clipping through hoods

### ISSUE THREAD

**Issue by Furbygeddon** [PierreDespereaux/Keizaal#81]
**Keizaal version**
3.5.2

**Describe the bug**
Female hair 16 is not working correctly and clips through hoods

**To reproduce**
Choose female hair 16 and equip hood

**Expected behavior**
Baldness when equipping a hood

**Screenshots**
Attached
![unknown](https://user-images.githubusercontent.com/68538230/105511657-6d33db00-5cd0-11eb-9d39-382af2d94c54.png)

**Comment by PierreDespereaux** [comment]
I have disabled this hair until I can get a proper fix in order.

**Comment by PierreDespereaux** [comment]
I'm keeping this style disabled for the foreseeable future.
