### ISSUE TITLE
Stay At The Systems Page - Updated

### ISSUE THREAD

**Issue by Shade088** [PierreDespereaux/Keizaal#87]
**Mod name**
Stay At The Systems Page - Updated

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/19832?tab=description

**Why?**
It is convenient to have the Esc key lead directly to the save menu for those who use keyboard & mouse.

**Additional context**
I suggest leaving this as an optional mod. Since it is an SKSE plugin that uses the Address Library for SKSE Plugins, it does not have to be updated. As far as I can tell, there are no downsides to having this mod under the optional tab. Leaving it under optional means that players who prefer to have the Esc key lead to the journal menu would not be affected.

**Comment by PierreDespereaux** [comment]
Accepted as an optional mod.
