### ISSUE TITLE
More Thalmor in the College of Winterhold Quests Recommendation

### ISSUE THREAD

**Issue by Aosana** [PierreDespereaux/Keizaal#88]
**Mod name**
More Thalmor in the College of Winterhold Quests

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/44735

**Why?**
With the recent inclusion of Catir's wonderful "Catir's College Creatures" mod, I think adding more content/difficulty to the College of Winterhold questline would be nice! This mod makes the Thalmor presence relating to the Eye of Magnus more significant.

**Comment by PierreDespereaux** [comment]
Ambushes are added before Ancano's treachery is even revealed.
