### ISSUE TITLE
Standalone Sleeves of Skyrim

### ISSUE THREAD

**Issue by CANicholson** [PierreDespereaux/Keizaal#9]
**Mod name**
Standalone Sleeves of Skyrim

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/42865

**Why?**
A simple vanilla+ add-on that adds some much-needed variation in low level Skyrim without removing a core element of Skyrim, the large half naked people running at you

**Additional context**
I'm currently working through various other factions(Imperial and Forsworn) and armors/clothes to add to the mod and plan on wrapping it up in FOMOD once different factions have been given armour. Currently, I recommend using this alongside Sleeves for Guards #10 as I will be tying that into my installer for Stormcloaks/Guards

**Comment by PierreDespereaux** [comment]
Will be properly reviewed upon FOMOD update.

**Comment by PierreDespereaux** [comment]
I'm going to go ahead an accept these, however I won't be adding them to Keizaal until your "final update" is out.

**Comment by PierreDespereaux** [comment]
Will be added in Keizaal 3.4.5

**Comment by PierreDespereaux** [comment]
Closing this issue. Will reopen in the future.
