### ISSUE TITLE
NPC missing in Markarth

### ISSUE THREAD

**Issue by hazmatec** [PierreDespereaux/Keizaal#90]
*Keizaal version
3.5.2

Describe the bug
Upon entering Markarth the first time, during the Forsworn attack the woman that is murdered is missing

To reproduce
Enter Markarth and wait for the scene to playout, a man will be sneaking with dagger in hand

Expected behavior
When the murder is happening, a women should be present

Screenshots
![20210124061229_1](https://user-images.githubusercontent.com/77921178/105629147-49c37a00-5e0f-11eb-9840-00dfed02cdf5.jpg)

Additional context
I am using Skyrim Unbound Reborn, and the Pit Fighter mods from optionals, not sure if this is what is causing the bug

**Comment by PierreDespereaux** [comment]
this is semi-common in Vanilla Skyrim. I'll check to see if it's consistently reproducible.

**Comment by PierreDespereaux** [comment]
Could not replicate.
