### ISSUE TITLE
Cresty's Distant Mists/Obsidian Weathers Patch

### ISSUE THREAD

**Issue by Shade088** [PierreDespereaux/Keizaal#91]
**Keizaal version**
3.5.2

**Describe the bug**
The plugin for the Cresty's Distant Mists/Obsidian Weathers patch is placed above Obsidian Weathers. The patch lists Obsidian Weathers as a master.

**To reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
The patch is at 102 priority, Obsidian Weathers is at 120.

**Comment by PierreDespereaux** [comment]
thank you!
