### ISSUE TITLE
REMOVE OPEN CITIES

### ISSUE THREAD

**Issue by MediumLowQuality** [PierreDespereaux/Keizaal#92]
**Keizaal version**
3.5.2

**Describe the bug**
Tthis mod desroyred my game
This mod destroyed my game, what thefuck,  ihad a  good game! GOOOD GAME! I INSTAL GOOD MODSGOOD MODS I INSTTALL HIS NOW EVERYTHING IN THIS GAME IS A GIANT HEAD OF GEBRIS
LIKE WHATT THE f\*\*\* WHY I HAD A GREATTGAME THIS MOD DESTROYES IT?!! ALL GAME ISOVER FOR FOCK SAKES I HAVE GOOD GAME AND IT DESTTROYED WITH ONE STTUPID MOD I NEVER DOWNLOAD MOD AGAIN IF AGAIN NOT EVEN ONE WHA THE f\*\*\* f\*\*\*ing WHY IHA D A GEERATT GAME AN THIS MOD AND HIS GIVING HEADS DESTTROYIT

**Comment by PierreDespereaux** [comment]
I fixed it.

**Comment by Dapperbot28** [comment]
holy shit, what a fucking masterpiece of a fix request. Up there with the bible and the mcdonalds menu. Truly a sight to behold.
