### ISSUE TITLE
True Thane Recommendation

### ISSUE THREAD

**Issue by Parygone** [PierreDespereaux/Keizaal#93]
True Thane SE

https://www.nexusmods.com/skyrimspecialedition/mods/42891

It makes becoming a thane of the nine holds a lot more worthwhile. You get to choose your own housecarl, get a set of hold armour & ring & improve the weapon you receive when you are named Thane + more!

https://youtu.be/9aBKzY1PITU?t=324 & mod page.

**Comment by PierreDespereaux** [comment]
I reviewed this a few weeks ago on my own.
