### ISSUE TITLE
Eating Animations and Sounds Recommendation

### ISSUE THREAD

**Issue by Parygone** [PierreDespereaux/Keizaal#94]
Eating Animations and Sounds SE

https://www.nexusmods.com/skyrimspecialedition/mods/42602

Immersive unique eating animations & sounds when consuming different food items.

https://youtu.be/9aBKzY1PITU?t=78 & mod page.

**Comment by PierreDespereaux** [comment]
Too many incompatibilities. Will look into it in the future.
