### ISSUE TITLE
Serio's Cycle Hotkeys

### ISSUE THREAD

**Issue by CTRLex** [PierreDespereaux/Keizaal#97]
**Mod name**
Serio's Cycle Hotkeys

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/27184

**Why?**
It is complimentary to iEquip, and invaluable to a mage character swapping left/right spells, which iEquip doesn't handle with grace due to its cycle delays. Serio's allows a separate set of hotkeys (for example 1-9) that can each be set to cycle left/right hand items. 

At its core, it does what iEquip does - only much, much faster. You can set up on each hotkey an infinite number of "cycles" that a further press of the hotkey will equip. Cycles can be set to left or right hand only, in which case it does not unequip what is still equipped - this allows a mage to work through all of their spells on a cycle while keeping a ward/shield equipped.

The best part - it cycles just as fast as the vanilla hotkeys, which is it's main draw.

It is complimentary to iEquip as it does not have any hud elements - so it can be tricky in the base Serio's mod to tell what is equipped at any one time - however iEquip works perfectly as a visual hud for Serio's.

**Additional context**
Suggest it as an optional mod, as it's predominantly for those that have to swap hands/gear/spells often.

**Comment by PierreDespereaux** [comment]
accepted as optional
