### ISSUE TITLE
Solitude issues.

### ISSUE THREAD

**Issue by jlmurra2** [PierreDespereaux/Keizaal#98]
First of all, thank you for creating this mod list. I have tried all available mod lists on Wabbajack, and this is the only one I would play with, big lore buff here too.

I only have the Kaizaal mod list, and the creation club content installed.

The issues I am having Solitude are that within the first few days of a new game many of the npcs will die. Sometimes they simply disappear, then later I find their coffins in the catacombs. Other times I find their bodies at the base of the Solitude arch along the road. Often they are surrounded by apples.

This includes both vanilla npcs, and those added by Redbag's Solitude. I have tested this with several new games, which npcs die vary between new games.

The other issue is regarding the curved stairway added by Redbag's Solitude. At the base I see what appears to be a gray rock lod covering the entrance. It has no collision, so I walk though and find about halfway up their is another lod, this time a ground texture type.

Thank you for any help.

**Comment by PierreDespereaux** [comment]
Unfortunately Redbag's Solitude and OCS were removed in the most recent version of Keizaal, so there is no way for my to investigate these issues. I apologise.

**Comment by jlmurra2** [comment]
Thank you for the reply. So open cities was causing problems as well? I will update my Kaizeel installation as soon as I am able.

**Comment by PierreDespereaux** [comment]
I don't know what was causing your issue, but I sadly cannot investigate any further because those mods are no longer present in my own version of Keizaal.

The new version is not savegame compatible, just so you know.

**Comment by jlmurra2** [comment]
I assumed as much. Thanks again.
