### ISSUE TITLE
 creation club conflicts.

### ISSUE THREAD

**Issue by jlmurra2** [PierreDespereaux/Keizaal#99]
**Keizaal version**
4.0.0

**Describe the bug**

I have found two so far.

The first occurred when playing the quest added by the creation club Alternative Armors - Steel Soldier creation entitled, Over the Edge:  
https://en.m.uesp.net/wiki/Skyrim:Over_the_Edge

At the stage where I am instructed to read the note in the four shields tavern, the note spawns behind the wall in the void behind the counter. I used the console command tcl to get to it.

The second occurs when playing the quest Restoring Order added by the Saints & Seducers creation: https://en.m.uesp.net/wiki/Skyrim:Restoring_Order

When instructed to "Investigate the Solitude sewers", I am directed to enter a manhole in Solitude, yet I spawn in the sewer added by the Skyrim sewers mod, and cannot access the correct cell added by Saints & Seduce to continue the quest.

**To reproduce**
Attempt to complete either quest.

**Expected behavior**
I enjoy the Skyrim sewers mod, and the Rodryk's Dragon Bridge mod, but they seem to conflict with the creation club content. I hope they can be patched somehow.

Thank you for any help.

**Comment by PierreDespereaux** [comment]
Try this patch for Saints and Seducers.
https://drive.google.com/open?id=119XRYPsvKevhXnXv60NTfu35eNce8EJx

As for Steel Soldier, I've never used the Creation so I don't have a patch for it. I'll look into including one next update.

**Comment by jlmurra2** [comment]
Great. Thank you for the quick reply.

**Comment by PierreDespereaux** [comment]
Rerun Wabbajack, the patches should be there now.

**Comment by jlmurra2** [comment]
For both? I will be able to update the installation this evening. Looking forward to it. Thank you.

**Comment by jlmurra2** [comment]
Updated , and tested. Both issues resolved, and working perfectly now.

Thank you.
